spring:
#  we can set the environment like the following codes instead of defining in environment variables
#  profiles:
#    active: dev
  application:
    name: note_app
  data:
    mongodb:
      #   connection string the server needs to connect to database (shouldn't be hardcoded)
      uri: ${MONGODB_CONNECTION_STRING}
      #   this is an opt-in for index creation (only then this @Indexed(expireAfter = "0s") in RefreshToken model will work)
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: 8085

jwt:
  secret: ${JWT_SECRET_BASE64}

# custom values to have access to in the code
notes:
  search:
    ignore-case: true
    min-length: 3
  validation:
    min-content-length: 5
    max-content-length: 500
    require_author: true
    allowed-categories:
      - "motivational"
      - "funny"
      - "tech"
