spring:
  application:
    name: note_app
  data:
    mongodb:
      #   connection string the server needs to connect to database (shouldn't be hardcoded)
      uri: ${MONGODB_CONNECTION_STRING}
      #   this is an opt-in for index creation (only then this @Indexed(expireAfter = "0s") in RefreshToken model will work)
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: 8085

jwt:
  secret: ${JWT_SECRET_BASE64}

#   to set a static password for basic authentication (for testing purposes)
#spring.security.user.password=test
